# Generated by Django 5.0.2 on 2024-02-26 13:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_author_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
