# Generated by Django 5.0.2 on 2024-02-28 08:58

import precise_bbcode.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_comment_content_alter_reply_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
        ),
    ]
