# Generated by Django 5.0.2 on 2024-02-28 09:03

import precise_bbcode.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post__content_rendered_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=precise_bbcode.fields.BBCodeTextField(no_rendered_field=True),
        ),
    ]
