# Generated by Django 5.0.2 on 2024-02-28 09:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_comment__content_rendered_reply__content_rendered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='_content_rendered',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='_content_rendered',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
