# Generated by Django 5.0.2 on 2024-02-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_category_description_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main.category'),
        ),
    ]
