# Generated by Django 5.0.2 on 2024-03-14 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_comment_content_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
