# Generated by Django 5.0.2 on 2024-03-17 16:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_post_subscribers_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
