# Generated by Django 5.0.2 on 2024-03-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_notifications_comment_or_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='reason',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
