# Generated by Django 5.0.2 on 2024-03-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_author_email_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='steam_uid',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
